name: Continuous Integration

on: push

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          npm install
          npm install maplibre-gl
          npm run build
          npm run ls la